name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install HTML5Validator
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Replace with your desired Python version
      - name: Install html5validator
        run: |
          pip install html5validator


      - name: Build Web Application
        run: |
          # No need to build static website

      - name: Validate HTML/CSS
        run: |
          html5validator index.html
          npx stylelint styles.css

      - name: Create Build Artifact
        run: |
          zip -r app.zip index.html script.js styles.css

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: web-app
          path: app.zip

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: web-app
          path: app

      - name: Deploy to GitHub Pages
        run: |
          cp -r app/* /im-sahiljain/CI-CD_Pipeline_Deployment-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
