name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install HTML5Validator
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  
      - name: Install html5validator
        run: |
          pip install html5validator

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  

      - name: Build Web Application
        run: |
          # No need to build static website

      - name: Validate HTML/CSS
        run: |
          html5validator index.html

      - name: Create Build Artifact
        run: |
          zip -r app.zip index.html script.js styles.css

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: web-app
          path: app.zip

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: web-app
          path: app

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
  
          mkdir temp-gh-pages
          mv app/* temp-gh-pages
            
          git init
  
         
          git add .
          git commit -m "Deploy to GitHub Pages"
  
          git push --force "https://${{ github.token }}@github.com/${{ github.repository }}.git" HEAD:gh-pages

          #git push --force "https://${{ github.token }}@github.com/${{ github.repository }}.git" master:gh-pages
  
         
          rm -rf temp-gh-pages
  
          
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
