name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          npm install

      - name: Build Web Application
        run: |
          npm run build

      - name: Validate HTML/CSS
        run: |
          html5validator index.html
          npx stylelint styles.css

      - name: Create Build Artifact
        run: |
          tar -czf app.tar.gz build/*

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: web-app
          path: app.tar.gz

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: web-app
          path: app

      - name: Deploy to GitHub Pages
        run: |
          bundle exec jekyll build -d public
          mv public/* ./
        env:
          GITHUB_TOKEN: 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
